services:
  jupyter:
    image: nvcr.io/nvidia/pytorch:25.04-py3
    ports:
      - "8888:8888"
      - "8889:8889"
    volumes:
      - type: bind
        source: ../data-model-parallelism/workspace
        target: /workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: '2gb'
    command: >
      sh -c "pip install jupyterlab-nvdashboard && tensorboard --logdir=/logs --port 8889 & exec jupyter-lab --no-browser --allow-root --ip=0.0.0.0 --port=8888 --NotebookApp.token='' --notebook-dir=/workspace/"
